/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TypeIndexRouteImport } from './routes/$type/index'
import { Route as TypeIdIndexRouteImport } from './routes/$type/$id/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeIndexRoute = TypeIndexRouteImport.update({
  id: '/$type/',
  path: '/$type/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeIdIndexRoute = TypeIdIndexRouteImport.update({
  id: '/$type/$id/',
  path: '/$type/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/$type/': typeof TypeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$type/$id/': typeof TypeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/$type': typeof TypeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$type/$id': typeof TypeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/$type/': typeof TypeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$type/$id/': typeof TypeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/$type/' | '/api/auth/$' | '/$type/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/$type' | '/api/auth/$' | '/$type/$id'
  id: '__root__' | '/' | '/sign-in' | '/$type/' | '/api/auth/$' | '/$type/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  TypeIndexRoute: typeof TypeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TypeIdIndexRoute: typeof TypeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/': {
      id: '/$type/'
      path: '/$type'
      fullPath: '/$type/'
      preLoaderRoute: typeof TypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$type/$id/': {
      id: '/$type/$id/'
      path: '/$type/$id'
      fullPath: '/$type/$id/'
      preLoaderRoute: typeof TypeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  TypeIndexRoute: TypeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TypeIdIndexRoute: TypeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
