/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as RecommendationsRouteRouteImport } from './routes/recommendations/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations/index'
import { Route as TypeIndexRouteImport } from './routes/$type/index'
import { Route as RecommendationsAllRouteImport } from './routes/recommendations/all'
import { Route as TypeIdIndexRouteImport } from './routes/$type/$id/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRouteRoute = RecommendationsRouteRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecommendationsRouteRoute,
} as any)
const TypeIndexRoute = TypeIndexRouteImport.update({
  id: '/$type/',
  path: '/$type/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsAllRoute = RecommendationsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => RecommendationsRouteRoute,
} as any)
const TypeIdIndexRoute = TypeIdIndexRouteImport.update({
  id: '/$type/$id/',
  path: '/$type/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/recommendations': typeof RecommendationsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/recommendations/all': typeof RecommendationsAllRoute
  '/$type/': typeof TypeIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$type/$id/': typeof TypeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/recommendations/all': typeof RecommendationsAllRoute
  '/$type': typeof TypeIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$type/$id': typeof TypeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/recommendations': typeof RecommendationsRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/recommendations/all': typeof RecommendationsAllRoute
  '/$type/': typeof TypeIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$type/$id/': typeof TypeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/recommendations'
    | '/sign-in'
    | '/recommendations/all'
    | '/$type/'
    | '/recommendations/'
    | '/api/auth/$'
    | '/$type/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/recommendations/all'
    | '/$type'
    | '/recommendations'
    | '/api/auth/$'
    | '/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/recommendations'
    | '/sign-in'
    | '/recommendations/all'
    | '/$type/'
    | '/recommendations/'
    | '/api/auth/$'
    | '/$type/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RecommendationsRouteRoute: typeof RecommendationsRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  TypeIndexRoute: typeof TypeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  TypeIdIndexRoute: typeof TypeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof RecommendationsRouteRoute
    }
    '/$type/': {
      id: '/$type/'
      path: '/$type'
      fullPath: '/$type/'
      preLoaderRoute: typeof TypeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/all': {
      id: '/recommendations/all'
      path: '/all'
      fullPath: '/recommendations/all'
      preLoaderRoute: typeof RecommendationsAllRouteImport
      parentRoute: typeof RecommendationsRouteRoute
    }
    '/$type/$id/': {
      id: '/$type/$id/'
      path: '/$type/$id'
      fullPath: '/$type/$id/'
      preLoaderRoute: typeof TypeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecommendationsRouteRouteChildren {
  RecommendationsAllRoute: typeof RecommendationsAllRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
}

const RecommendationsRouteRouteChildren: RecommendationsRouteRouteChildren = {
  RecommendationsAllRoute: RecommendationsAllRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
}

const RecommendationsRouteRouteWithChildren =
  RecommendationsRouteRoute._addFileChildren(RecommendationsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RecommendationsRouteRoute: RecommendationsRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  TypeIndexRoute: TypeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  TypeIdIndexRoute: TypeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
